### ISSUE TITLE
Open311 GeoReport v2 coverage

### ISSUE THREAD

**Issue by pwalsh** [govflow/govflow#4]
TBD

https://wiki.open311.org/GeoReport_v2/

# Tasks

- [ ] Methods
  - [ ] Service Discovery
    - [ ] JSON
    - [ ] XML
  - [x] GET Service List
    - [x] JSON
    - [x] XML
  - [ ] GET Service Definition
    - [ ] JSON
    - [ ] XML
  - [ ] POST Service Request
    - [x] JSON
    - [ ] XML
  - [ ] GET service_request_id from a token
    - [ ] JSON
    - [ ] XML
  - [ ] GET Service Requests
    - [ ] JSON
    - [ ] XML
  - [ ] GET Service Request
    - [ ] JSON
    - [ ] XML
- [ ] Errors https://wiki.open311.org/GeoReport_v2/#errors

**Comment by noamoss** [comment]
@pwalsh 

The [open 311 scheme](http://wiki.open311.org/GeoReport_v2/#specification) also includes a `service notice` field:
```
Information about the action is expected to fulfill the request or otherwise address the information reported.
````
Do we hold and/or use this field right now for service requests?

**Comment by pwalsh** [comment]
@noamoss we don't respond with this field, which is an optional field. Do you see a use case for it at present?

Even though we don't have clear user needs right now for Open311 support, I'd be happy to get our coverage of the spec close to 100%

**Comment by noamoss** [comment]
@pwalsh I gues it is not needed now, as we are dealing with very simple workflows but I think this field will actually provide important information about the service request.

**Comment by noamoss** [comment]
@pwalsh see this real-world example: "....we couldn't do the graffiti because we don't have the paint. So we had to procure the paint and that's what's holding up the graffiti getting covered because we don't have the materials and we're stuck into a procurement process that's hindered by a supply chain problem, right? We don't have that piece of it."
